- name: Deploy MERN Application
  hosts: web_servers
  become: true
  tasks:
    - name: Configure Environment Variables
      copy:
        dest: /var/www/mern-app/.env
        content: |
          DB_HOST={{ hostvars['dbserver']['ansible_host'] }}
          DB_USER=your_user
          DB_PASS=your_password
          DB_NAME=mernApp
          PORT=3000
          JWT_SECRET=superSecret

    - name: Start Node.js Application
      command: npm start
      args:
        chdir: /var/www/mern-app
